name: CI checks

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - ready_for_review
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.14"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest ruff
    - name: Analyse and test the code
      run: |
        ruff check
        pytest
