name: CI checks

on: 
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
   
jobs:
  build_and_test:
    name: build_and_test
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version-file: "pyproject.toml"
    - name: Install uv
      uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
    - name: Install the project
      run: uv sync --locked --all-extras --dev
    - name: Run ruff
      run: uv run ruff check
    - name: Run tests
      run: uv run pytest tests
